// TRANSACTION
export const UNDO_TRANSACTION = "UNDO_TRANSACTION";
export const NEW_TRANSACTION = "NEW_TRANSACTION";

// USER
export const UPDATE_USER = "UPDATE_USER";
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";
